source "https://rubygems.org"
ruby "1.9.3"

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'

# Use Thin for our web server
gem 'thin'

gem 'activesupport'
gem 'activerecord'

gem 'rake'
gem 'faker'


gem 'oauth'
gem 'twitter'

group :development, :test do
	gem 'shotgun'
  gem 'rspec'
end
